sls:
  url: ${SLS_HOST_URL}

hapi-fhir:
  url: ${HAPI_FHIR_URL}

spring:
  datasource:
    url: jdbc:mysql://google/${DB_NAME}?cloudSqlInstance=${CLOUD_SQL_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false
