# This CI workflow will: 
# Run the workflow on an Ubuntu environment doing this steps. 
#   Step 1) Checking out the Git project
#   Step 2) Set up JDK 11
#   Step 3) StepSet up a Maven Settings Action with sonatypeSnapshots enabled
#   Step 4) Maven Build and Package, tests skipped 
#   Step 5) Maven Verify and Run Unit Tests

name: Build Status
on:
  push:
    branches: 
    - master 
     - develop
  pull_request:
    branches: 
    - master
    - develop
jobs:
  build:
    name: Build and Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checking out the Git project
        uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Settings Action
        uses: s4u/maven-settings-action@v2.1.0
        with:
          sonatypeSnapshots: true
      - name: Maven Build and Package, tests skipped 
        run: mvn -B clean package -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Maven Verify and Run Unit Tests
        run: mvn -B clean verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
